<?php
return array (
  'autogenerated-13-c51ce410c124a10e0db5e4b97fc2af39' => 
  array (
    'base' => 'https://typo3demo.ddev.site/autogenerated-13',
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 13,
    'routes' => 
    array (
    ),
  ),
  'typo3-demo' => 
  array (
    'base' => 'https://typo3demo.ddev.site/',
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'Deutsch',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'de_DE',
        'navigationTitle' => 'DR',
        'flag' => 'de',
        'hreflang' => '',
        'websiteTitle' => '',
      ),
    ),
    'rootPageId' => 12,
    'websiteTitle' => '',
  ),
);
#